"""Modifications to task table

Revision ID: 796ef6fee1e2
Revises: 67146ec0dfb1
Create Date: 2026-02-12 22:09:18.634769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796ef6fee1e2'
down_revision: Union[str, Sequence[str], None] = '67146ec0dfb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'task')
    # ### end Alembic commands ###
